const Discord = require('discord.js')

var horseFacts = ['Horses can run shortly after birth.',
                  'Horses have around 205 bones in their skeleton.',
                  'Horses have bigger eyes than any other mammal that lives on land.',
                  'Because horse\’s eyes are on the side of their head they are capable of seeing nearly 360 degrees at one time.',
                  'Horses gallop at around 27 mph.',
                  'The fastest recorded sprinting speed of a horse was 55 mph.',
                  'When horses look like they’re laughing, they’re actually engaging in a special nose-enhancing technique known as “flehmen,” to determine whether a smell is good or bad.',
                  'Horse hooves are made from the same protein that comprises human hair and fingernails.',
                  'Horses use their ears, eyes and nostrils to express their mood. They also communicate their feelings through facial expressions.',
                  'A horse can see better at night than a human. However, it takes a horse\'s eyes longer to adjust from light to dark and from dark to light than a human\'s.',
                  'Horses with pink skin can get a sunburn.',
                  'You can tell if a horse is cold by feeling behind their ears. If that area is cold, so is the horse.',
                  'Horses are social animals and will get lonely if kept alone, and they will mourn the passing of a companion.',
                  'Horse’s ears have the ability to rotate 180 degrees.',
                  'Domestic horses have a lifespan of around 25 years.',
                  'A 19th century horse named ‘Old Billy’ is said to have lived 62 years.',
                  'Horses have been domesticated for over 5000 years',
                  'Horses are herbivores (plant eaters).',
                  'Al is not a horse (fact)',
                  'Horses have bigger eyes than any other mammal that lives on land.',
                  'Because horse’s eyes are on the side of their head they are capable of seeing nearly 360 degrees at one time.',
                  'A male horse is called a stallion.',
                  'A female horse is called a mare.',
                  'A young male horse is called a colt.',
                  'A young female horse is called a filly.',
                  'Ponies are small horses.',
                  'When horses look like they’re laughing, they’re actually engaging in a special nose-enhancing technique known as “flehmen,” to determine whether a smell is good or bad.',
                  'At one time people thought horses were colorblind. They’re not, though they are better at seeing yellows and greens than purples and violets.',
                  'A horse\'s teeth take up a larger amount of space in their head than their brain.',
                  'The horse trailer (“horse box”) was invented by Lord George Bentinck, a U.K. man who needed a more effective transport for getting his six horses from one racetrack to another.',
                  'In 1872, Leland Stanford (1824-1893) made a bet that at some point in the gallop all four of a horse’s legs are off the ground at the same time. Eadweard Muybridge (1830-1904) proved him right by using a series of 24 cameras and photographing a racehorse named Sallie Gardner.',
                  'Horses are more secure and comfortable when trailering if they can face the rear, but they prefer openings.',
                  'The Przewalski’s horse is the only truly wild horse species still in existence. The only wild population is in Mongolia. There are however numerous populations across the world of feral horses e.g. mustangs in North America.',
                  'The fastest recorded sprinting speed of a horse was 88 kph (55 mph). Most gallop at around 44 kph or 27 mph.',
                  'Horses use their ears, eyes and nostrils to express their mood. They also communicate their feelings through facial expressions.',
                  'Horses will not lie down simultaneously because at least one will act as a look-out to alert its companions of potential dangers.',
                  'Vocalizations are highly important to horses. Examples: Whinnying and neighing sounds are elicited when horses meet or leave each other. Stallions (adult male horses) perform loud roars as mating calls, and all horses will use snorts to alert others of potential danger.',
                  'An adult horse’s brain weights 22 oz, about half that of a human.',
                  'Horses still hold a place of honor in many cultures, often linked to heroic exploits in war, China being one of those countries.',
                  'Horses can not vomit.',
                  'There is only one species of domestic horse, but around 400 different breeds that specialize in everything from pulling wagons to racing. All horses are grazers',
                  'A horse can see better at night than a human. However, it takes a horse\'s eyes longer to adjust from light to dark and from dark to light than a human\'s',
                  'The first cloned horse was a Haflinger mare in Italy in 2003',
                  'Horses like sweet flavors and will usually reject anything sour or bitter',
                  'Wild horses generally gather in groups of 3 to 20 animals. A stallion (mature male) leads the group, which consists of mares (females) and young foals. When young males become colts, at around two years of age, the stallion drives them away. The colts then roam with other young males until they can gather their own band of females.',
                  'Most of the time, wherever a horse\'s ear is pointing is where the horse is looking with the eye on the same side. If the ears are pointing in different directions, the horse is looking at two different things at the same time.',
                  'Horses produce approximately 10 gallons of saliva a day',
                  'On the underside of a horse\'s hoof is a triangular shaped area called the “frog," which acts as a shock absorber for a horse\'s leg, and also helps to pump blood back up the leg.',
                  'Horses height is measured in units known as "hands." One hand is equal to four inches. The tallest horse on record was a Shire named Sampson. He was 21.2 hands (7 feet, 2 inches) tall. He was born in 1846 in Toddington Mills, England',
                  'The average horse\'s heart weighs approximately 9 or 10 pounds',
                  'Scientists believe that the first known ancestor of the horse lived about 50 million years ago. This prehistoric horse is called Eohippus and had four padded toes on the front legs and three padded toes on the back legs.',
                  'Horses with typical anatomy are "obligate nasal breathers" which means they must breathe through their nostrils and cannot breathe through their mouths.',
                  'Horses drink at least 25 gallons of water a day (more in hotter climates).',
                  'It takes 9-12 months to re-grow an entire horse hoof.',
                  'Horses with pink skin can get a sunburn.',
                  'A zebroid is a cross between a zebra and any other member of the Equidae family (which, besides zebras, includes donkeys, ponies, and horses.)',
                  'A "zonky" is a cross between a zebra and a donkey.',
                  'A "zony" is a cross between a zebra and a pony.',
                  'A "zorse" is a cross between a zebra and a horse.',
                  'You can tell if a horse is cold by feeling behind their ears. If that area is cold, so is the horse.',
                  'Horses have 16 muscles in each ear, allowing them to rotate their ears 180 degrees.',
                  'If a horse has a red ribbon on it’s tail, it kicks.',
                  'Horses are social animals and will get lonely if kept alone, and they will mourn the passing of a companion.',
                 ]

module.exports = {
  name: 'horse',
  description: 'Replies with a horse fact',
  expectedArgs: '',
  category: 'Facts',
  permissionError: '',
  minArgs: 0,
  maxArgs: 1,
  callback: async (message, paramsCom) => {
    console.log(message.author.tag + ' horse');
    var horseNum = await Math.floor((Math.random() * horseFacts.length));
    message.reply(horseFacts[horseNum]);
  },
  permissions: [],
  requiredRoles: [],
}
